<inh f='include/c++/4.8/exception' l='60' c='std::exception'/>
<def f='include/c++/4.8/ext/concurrence.h' l='91' ll='97'/>
<size>8</size>
<fun r='__gnu_cxx::__concurrence_wait_error::what'/>
