<dec f='include/python2.7/pyerrors.h' l='217' type='void _PyErr_BadInternalCall(char * filename, int lineno)'/>
